[bumpver]
current_version = "2.0.1rc5"
version_pattern = "MAJOR.MINOR.PATCH[PYTAGNUM]"
commit_message  = "chore(release): {new_version}"
#tag_message     = "Release {new_version}"
#tag_scope       = "default"
commit          = true
tag             = false
#tag_name        = "v{version}"

[bumpver.file_patterns]
"pyproject.toml" = [
  'version = "{version}"'
]
"src/cisco_hashgen/__init__.py" = [
  '__version__ = "{version}"'
]
