name: Publish (PyPI)

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'      # v2.0.0, v2.1.3, etc.

permissions:
  id-token: write                    # OIDC / Trusted Publishing
  contents: write                    # create GitHub Releases

jobs:
  build-publish:
    name: Build & Publish to PyPI + Create GH Release
    runs-on: ubuntu-latest
    if: "!contains(github.ref_name, 'rc')"  # exclude RC tags
    environment: pypi-prod

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install build tools
        run: python -m pip install --upgrade build twine

      - name: Build dists
        run: python -m build

      - name: Twine check
        run: python -m twine check dist/*

      - name: Publish to PyPI (Trusted Publishing)
        uses: pypa/gh-action-pypi-publish@release/v1

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          files: |
            dist/*
          body_path: docs/releases/release-notes-${{ github.ref_name }}.md
